name: Basic pull request checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main repo
        uses: actions/checkout@v2

      - name: PHP Syntax Checker (Lint)
        uses: ./.github/actions/lint

      - name: PHP style checks (phpcs)
        uses: ./.github/actions/style-check
